### ISSUE TITLE
rocs_maxconfs_output is not used

### ISSUE THREAD

**Issue by gandrianov** [pkiruba/Rosetta_Kinase_CM#1]
Hi Kiruba,

It seems like rocs_maxconfs_output hardcoded and people cannot change it

https://github.com/pkiruba/Rosetta_Kinase_CM/blob/1eaace8dd67bb793fbe0d63b16058af30fb9c3dd/modeling_script.py#L44

**Comment by gandrianov** [comment]
Probably `100` should be argument of function

https://github.com/pkiruba/Rosetta_Kinase_CM/blob/1eaace8dd67bb793fbe0d63b16058af30fb9c3dd/modeling_script.py#L67

**Comment by pkiruba** [comment]
@gandrianov I agree with your point. We can make it as an argument. Please feel free to update it.
